### ISSUE TITLE
calicoctl KeyError: 'affinity'

### ISSUE THREAD

**Issue by CaoShuFeng** [projectcalico/calico-containers#1279] opened 2016-11-07 08:04 UTC
When deleting a node, I get this:
$ sudo ETCD_ENDPOINTS=http://172.16.19.137:2379 ./calicoctl node remove
KeyError: 'affinity'

Traceback (most recent call last):
  File "<string>", line 144, in <module>
  File "calico_ctl/node.py", line 228, in node
  File "calico_ctl/node.py", line 667, in node_remove
  File "site-packages/pycalico/datastore.py", line 133, in wrapped
  File "site-packages/pycalico/ipam.py", line 1308, in remove_ipam_host
  File "site-packages/pycalico/datastore.py", line 133, in wrapped
  File "site-packages/pycalico/ipam.py", line 1262, in release_host_affinities
  File "site-packages/pycalico/ipam.py", line 264, in _release_block_affinity
  File "site-packages/pycalico/ipam.py", line 74, in _read_block
  File "site-packages/pycalico/block.py", line 150, in from_etcd_result
KeyError: 'affinity'

$ sudo ETCD_ENDPOINTS=http://172.16.19.137:2379 ./calicoctl version
0.22.0-dev

This is diags file:
https://transfer.sh/LnW51/diags-071116-054929.tar.gz

**Comment by CaoShuFeng** [comment] 2016-11-07 08:27
Hi, I known the reason of this issue. Can I fix it myself?
Also I think this need to be fixed in libcalico.

**Comment by caseydavenport** [comment] 2016-11-07 17:01
@CaoShuFeng I'll take a look at that PR :)

However, I'm going to close this issue as a duplicate of https://github.com/projectcalico/calico-containers/issues/1194#issuecomment-256553868

**Closed by caseydavenport** 2016-11-07 17:01 UTC
