### ISSUE TITLE
Setting CALICO_DISABLE_FILE_LOGGING=true leads to failed rkt calico-node container startup

### ISSUE THREAD

**Issue by ae6rt** [projectcalico/calico-containers#1120] opened 2016-08-18 18:25 UTC
Given this development-mode script to start calico-node under rkt

```
systemd-run --slice=machine rkt run \
    --stage1-path=/usr/lib/rkt/stage1-fly.aci \
    --insecure-options=image \
    --volume=birdctl,kind=host,source=/var/run/calico,readOnly=false \
    --mount volume=birdctl,target=/var/run/calico \
    --volume=modules,kind=host,source=/lib/modules,readOnly=false \
    --mount volume=modules,target=/lib/modules \
    --volume=certs,kind=host,source=/etc/ssl/certs,readOnly=true \
    --mount volume=certs,target=/etc/ssl/certs \
    --volume=keys,kind=host,source=/etc/ssl/private,readOnly=true \
    --mount volume=keys,target=/etc/ssl/private \
    --volume=hosts,kind=host,source=/etc/hosts,readOnly=true \
    --mount volume=hosts,target=/etc/hosts \
    --set-env=CALICO_DISABLE_FILE_LOGGING=true \
    --set-env HOSTNAME=ip-10-2-23-155.qa.xoom.com  \
    --set-env IP=10.2.23.155  \
    --set-env AS=64511  \
    --set-env NO_DEFAULT_POOLS=  \
    --set-env ETCD_ENDPOINTS=https://etcd01:2379,https://etcd02:2379,https://etcd03:2379  \
    --set-env ETCD_CA_CERT_FILE=/etc/ssl/certs/cacert.pem  \
    --set-env ETCD_KEY_FILE=/etc/ssl/private/calico-etcd-key.pem  \
    --set-env ETCD_CERT_FILE=/etc/ssl/certs/calico-etcd.pem  \
    docker://calico/node:v0.21.0
```

I find this in journalctl logs, which indicates some problems starting the runsv services:

```
$ sudo ./rkt-calico.sh 
Running as unit run-6466.service.
[centos@ip-10-2-23-155 ~]$ sudo journalctl -u run-6466
-- Logs begin at Mon 2016-08-15 22:15:18 UTC, end at Thu 2016-08-18 18:19:52 UTC. --
Aug 18 18:19:44 ip-10-2-23-155.qa.xoom.com systemd[1]: Started /bin/rkt run --stage1-path=/usr/lib/rkt/stage1-fly.aci --insecure-options=image --volume=birdctl,kind=host,source=/var/run/calico,readOnly=fa
Aug 18 18:19:44 ip-10-2-23-155.qa.xoom.com systemd[1]: Starting /bin/rkt run --stage1-path=/usr/lib/rkt/stage1-fly.aci --insecure-options=image --volume=birdctl,kind=host,source=/var/run/calico,readOnly=f
Aug 18 18:19:44 ip-10-2-23-155.qa.xoom.com rkt[6467]: image: using image from file /usr/lib/rkt/stage1-fly.aci
Aug 18 18:19:45 ip-10-2-23-155.qa.xoom.com rkt[6467]: image: using image from local store for url docker://calico/node:v0.21.0
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: rm: can't remove '/etc/service/bird/log': Directory not empty
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: rm: can't remove '/etc/service/bird6/log': Directory not empty
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: rm: can't remove '/etc/service/confd/log': Directory not empty
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: rm: can't remove '/etc/service/felix/log': Directory not empty
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: Calico node started successfully
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv felix: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird6: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:46 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv confd: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:47 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:47 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird6: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:47 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv confd: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:47 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv felix: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:48 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird6: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:48 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:48 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv confd: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:48 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv felix: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:49 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv felix: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:49 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:49 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird6: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:49 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv confd: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:50 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv felix: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:50 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:50 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird6: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:50 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv confd: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:51 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv felix: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:51 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird6: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:51 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:51 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv confd: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:52 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv felix: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:52 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird6: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:52 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv bird: fatal: unable to start log/./run: file does not exist
Aug 18 18:19:52 ip-10-2-23-155.qa.xoom.com rkt[6467]: runsv confd: fatal: unable to start log/./run: file does not exist
```

If I remove 

```
    --set-env=CALICO_DISABLE_FILE_LOGGING=true \
```
The services startup without incident.

@caseydavenport

**Comment by caseydavenport** [comment] 2016-08-19 17:54
I've just tried reproducing this, though with some minor differences since I'm not using a clustered / TLS enabled etcd.

```
systemd-run --slice=machine rkt run \
    --stage1-path=/usr/lib64/rkt/stage1-images/stage1-fly.aci \
    --insecure-options=image \
    --volume=birdctl,kind=host,source=/var/run/calico,readOnly=false \
    --mount volume=birdctl,target=/var/run/calico \
    --volume=modules,kind=host,source=/lib/modules,readOnly=false \
    --mount volume=modules,target=/lib/modules \
    --volume=hosts,kind=host,source=/etc/hosts,readOnly=true \
    --mount volume=hosts,target=/etc/hosts \
    --set-env=CALICO_DISABLE_FILE_LOGGING=true \
    --set-env HOSTNAME=172.18.18.101  \
    --set-env IP=172.18.18.101  \
    --set-env AS=64511  \
    --set-env NO_DEFAULT_POOLS=  \
    --set-env ETCD_ENDPOINTS=http://localhost:2379 \
    docker://calico/node:v0.21.0
```

However, everything seems to start just fine.  Some more info:

```
core@calico-01 ~ $ rkt version
rkt Version: 1.11.0
appc Version: 0.8.5
Go Version: go1.5.4
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```

OS Version:
```
coreos-alpha  (virtualbox, 1122.0.0)
```

**Comment by ae6rt** [comment] 2016-08-19 19:47
Here is my environment:

```
[centos@ip-10-2-23-226 ~]$ rkt version
rkt Version: 1.12.0
appc Version: 0.8.5
Go Version: go1.6.2
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
[centos@ip-10-2-23-226 ~]$ printf "$(rkt version)\n--\n$(uname -srm)\n--\n$(cat /etc/os-release)\n--\n$(systemctl --version)\n"
rkt Version: 1.12.0
appc Version: 0.8.5
Go Version: go1.6.2
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
--
Linux 3.10.0-327.10.1.el7.x86_64 x86_64
--
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
--
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by caseydavenport** [comment] 2016-10-27 06:14
Closing as not reproducible for now.

Please comment / re-open if encountered again.

**Closed by caseydavenport** 2016-10-27 06:14 UTC
Labels: area/rkt, kind/bug, priority/P3

**Comment by alexey-medvedchikov** [comment] 2017-01-30 16:56
The problem is on docker + overlay and centos 7 kernel you have:

```
/ # strace -f rm -r /etc/service/available/bird/log
execve("/bin/rm", ["rm", "-r", "/etc/service/available/bird/log"], [/* 35 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7f070e936b28) = 0
set_tid_address(0x7f070e936b60)         = 277
mprotect(0x7f070e933000, 4096, PROT_READ) = 0
mprotect(0x7f070ebf8000, 16384, PROT_READ) = 0
getuid()                                = 0
lstat("/etc/service/available/bird/log", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
access("/etc/service/available/bird/log", W_OK) = 0
open("/etc/service/available/bird/log", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
getdents64(3, /* 2 entries */, 2048)    = 48
getdents64(3, /* 0 entries */, 2048)    = 0
close(3)                                = 0
rmdir("/etc/service/available/bird/log") = -1 EINVAL (Invalid argument)
write(2, "rm: can't remove '/etc/service/a"..., 69rm: can't remove '/etc/service/available/bird/log': Invalid argument
) = 69
exit_group(1)                           = ?
+++ exited with 1 +++
```

I think it can be solved by replacing sequence:
```
rm -r /etc/service/available/<svc>/log
mv /etc/service/available/<svc> /etc/service/enabled/
```
with
```
cp -a /etc/service/available/<svc> /etc/service/enabled/
rm -r /etc/service/enabled/<svc>/log
```

**Comment by alexey-medvedchikov** [comment] 2017-01-30 18:02
I've tested my suggestion and it works for me #1473
