### ISSUE TITLE
Setting ETCD_ENDPOINTS environment does not work

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-containers#1020] opened 2016-06-14 21:45 UTC
Reported by a user:

If you set the ETCD_ENDPOINTS environment, calicoctl launches the node container with he default ETCD_AUTHORITY value and the endpoints list is ignored.

For example:

```
ETCD_ENDPOINTS=http://192.0.2.121:2379,http://192.0.2.122:2379,http://192.0.2.123:2379 calicoctl node --libnetwork
Running Docker container with the following command:

docker run -d --restart=always --net=host --privileged --name=calico-node -e HOSTNAME=xxx-etcd-4 -e IP= -e IP6= -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -e ETCD_ENDPOINTS=http://192.0.2.121:2379,http://192.0.2.122:2379,http://192.0.2.123:2379 -v /var/log/calico:/var/log/calico -v /lib/modules:/lib/modules -v /var/run/calico:/var/run/calico calico/node:v0.19.0

Calico node is running with id: 4830dadcacbe661f9927ac87fdf93c74acd58e685f416a3f8594c5400088456c
Waiting for successful startup
No IP provided. Using detected IP: 192.0.2.124
Calico node started successfully
Calico libnetwork driver is running with id: 00f19602cef5454dbbfd8d94855b7d260f8c03d2ebbca52644edeaa0c80d7c23
```

**Comment by tomdee** [comment] 2016-06-29 00:40
We need a repro of this. It certainly looks like both env vars are being passed into the container.

**Comment by tomdee** [comment] 2016-06-29 00:41
What is ignoring it? Is it just the libnetwork plugin?

**Comment by tomdee** [comment] 2016-06-29 00:43
Might be a dupe of #1015

**Comment by ae6rt** [comment] 2016-07-06 14:35
I see something similar, but in an apparently simpler situation.  For calicoctl version v0.20.0, I see:

```
# export ETCD_ENDPOINTS=https://10.2.23.10:2379,https://10.2.23.11:2379,https://10.2.23.9:2379
# export AS_NUMBER=64511
# export ETCD_CA_CERT_FILE=/etc/ssl/certs/cacert.pem
# /opt/xoom/apps/calico/bin/calicoctl node --detach=false
Traceback (most recent call last):
  File "<string>", line 68, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "calico_ctl/bgp.py", line 38, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "calico_ctl/connectors.py", line 29, in <module>
  File "site-packages/pycalico/datastore.py", line 247, in __init__
  File "site-packages/etcd/client.py", line 204, in __init__
  File "site-packages/etcd/client.py", line 299, in machines
  File "site-packages/etcd/client.py", line 299, in machines
  File "site-packages/etcd/client.py", line 301, in machines
etcd.EtcdException: Could not get the list of servers, maybe you provided the wrong host(s) to connect to?
calicoctl returned -1
```

If I pare the list of etcd servers back to one, I see something different, but which still fails

```
# export ETCD_ENDPOINTS=https://10.2.23.10:2379
# /opt/xoom/apps/calico/bin/calicoctl node --detach=false
ERROR: Could not connect to etcd at https://10.2.23.10:2379
```

Yet the etcd server is available:

```
# telnet 10.2.23.10 2379
Trying 10.2.23.10...
Connected to 10.2.23.10.
Escape character is '^]'.
^CConnection closed by foreign host.
```

**Comment by ae6rt** [comment] 2016-07-06 16:16
Progress:  this works, namely specifying the etcd hosts as hostnames and not IP addresses.  I wish it weren't so strict.  This suggests that the TLS client in calicoctl is not prepared to use subject alternative names when considering whether to accept a server certificate.  Am I right?

```
# export ENDPOINTS=https://etcd01:2379,https://etcd02:2379,https://etcd03:2379
# /opt/xoom/apps/calico/bin/calicoctl node --detach=false
Running Docker container with the following command:

docker run --restart=always --net=host --privileged --name=calico-node -e HOSTNAME=ip-10-2-23-210.qa.xoom.com -e IP= -e IP6= -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v /lib/modules:/lib/modules -v /var/run/calico:/var/run/calico calico/node:v0.20.0

Calico node is running with id: de300e1701436330c74657dd6d70616a2003080ff4fe2c3f27464e86fee18c75
Waiting for successful startup
No IP provided. Using detected IP: 10.2.23.210
Calico node started successfully
```

**Comment by ae6rt** [comment] 2016-07-06 16:24
Actually, wait.  If I had only looked at what calicoctl claims it will run, I see no evidence that the https endpoints are actually honored.  It appears some validation on ETCD_ENDPOINTS is performed on startup, and this validation passes, but then the value is apparently ignored.  See in the output

```
-e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http
```

**Comment by matthewdupre** [comment] 2016-07-27 21:29
As far as the original report goes @robbrockbank it's normal that both values get passed through (notice ENDPOINTS is passed after the defaulted AUTHORITY).  

On the other hand, that doesn't really explain @ae6rt's results.  Could you please confirm the calicoctl version you're using?

**Comment by ae6rt** [comment] 2016-07-27 21:37
I am using calicoctl version

```
[centos@ip-10-2-23-176 ~]$ sudo -E /opt/xoom/apps/calico/bin/calicoctl version
0.20.0
```
and can confirm that ETCD_ENDPOINTS is correctly read from the environment with this type of systemd service definition:

```
# /etc/systemd/system/calico-node.service
[Unit]
Description=calicoctl node
After=docker.service
Requires=docker.service

[Service]
User=root
EnvironmentFile=/etc/calico/calico-node.conf
PermissionsStartOnly=true
ExecStart=/opt/xoom/apps/calico/bin/calicoctl node --as=${AS_NUMBER} --detach=false
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

where /etc/calico/calico-node.conf looks like

```
# https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/KubernetesIntegration.md
#
# Because of this https://github.com/shazow/urllib3/issues/258 the URLs for the endpoint(s) must use hostnames and not IP addresses.  
ETCD_ENDPOINTS=https://etcd01:2379,https://etcd02:2379,https://etcd03:2379
AS_NUMBER=64511
ETCD_CA_CERT_FILE=/etc/ssl/certs/cacert.pem

# [msp 07Jul2016]i These files are required by calicoctl even if etcd does not demand client certs.  Track this issue for progress:  https://github.com/projectcalico/calico-containers/issues/1046
ETCD_KEY_FILE=/etc/ssl/private/calico-etcd-key.pem
ETCD_CERT_FILE=/etc/ssl/certs/calico-etcd.pem
```

**Comment by matthewdupre** [comment] 2016-07-27 21:56
And when hitting the issue calling calicoctl yourself you also had the ETCD_CA_CERT_FILE / CERT / KEY variables set?

**Comment by matthewdupre** [comment] 2016-07-27 22:54
OK - closing this :).

**Closed by matthewdupre** 2016-07-27 22:54 UTC
Labels: bug
