### ISSUE TITLE
Service IP responses can bypass kube-proxy

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#1008] opened 2016-06-03 11:39 UTC
User reached out on slack, having issues in this scenario:

- k8s nodes on same LAN segment
- Calico networking
- 2 compute nodes: node1 and node2
- service IP configured for a pod
- pod is running on node2
- try to connect to service IP via node1

Response packets come back with source IP being that of the pod rather than the service IP, as expected.  This scenario works with flannel.

I suspect the issue is that node2 has a return path to the external host that doesn't go via node1, where the NAT flow has been set up.

**Comment by caseydavenport** [comment] 2016-06-03 17:06
To make sure I understand, the traffic source was outside of the cluster and a route to the service IP range was set up to point at node1?  Rather than the traffic being originated on node1?

**Comment by fasaxc** [comment] 2016-06-03 17:35
Yes, that's correct. They were trying to use node1 as a gateway into the
cluster.

**Comment by fasaxc** [comment] 2016-06-29 08:52
It's a non-obvious consequence of how Calico does networking that you can't access a service VIP from outside the cluster.  I don't think k8s ever intended for service VIPs to be accessible from outside the cluster but, since it works with some other networking options, some people have come to expect it.   

Three possible options:

- Document it as an FAQ, along with the right way (which I think is to use a NodePort?).  
- Document a work-around, which would probably mean running a dedicate kube-proxy, also set up to be the router for a cluster (feel s icky)
- "Fix" kube-proxy to make this case work.

**Comment by caseydavenport** [comment] 2016-06-29 16:35
I would argue that this is not a bug - this is neither a recommended nor supported way to access services from outside of the cluster in Kubernetes (see NodePort, Ingress).

I wouldn't be opposed to documenting it in the FAQ (though I've only heard of this one instance where it was hit) but my impression right now is that we shouldn't go through hoops to make this work.

**Comment by lxpollitt** [comment] 2016-06-29 16:53
We do have some other users who have a desire to use service VIPs rather than node ports for accessing services from outside the cluster.  Essentially they want to have some dedicated nodes that they use as their ingress load balancers, but with kubeproxy being the load balancer itself (rather than separate e.g. HAProxy or NGINX).  

I'm not 100% sure what the advantages of that are.  I think the number of hops to reach the service would be the same (because ingress load balancers run on nodes in the cluster and the local kubeproxy on those nodes would do the normal iptables magic to point at a real pod).  I guess potentially one less thing to configure?

cc/ @liljenstolpe

**Comment by caseydavenport** [comment] 2016-09-14 04:58
Closing this, since I don't think it's a bug and it's currently not a valid way to access Services from outside of the cluster.

**Closed by caseydavenport** 2016-09-14 04:58 UTC
Labels: kubernetes
