### ISSUE TITLE
docs: aws deployment instructions stability

### ISSUE THREAD

**Issue by gosuri** [projectcalico/calico-containers#1148] opened 2016-09-12 07:08 UTC
I was wondering if AWS instructions (https://github.com/projectcalico/calico-containers/blob/master/docs/cni/kubernetes/AWS.md) has ever been tested?

we're trying to pitch calico to a customer and seeing a perpetual stream of issues like projectcalico/calico-cni#171

**Comment by fasaxc** [comment] 2016-09-12 08:05
projectcalico/calico-cni#171 is a new issue that we spotted on Friday; Calico seems to have been broken by k8s changes.  We've got someone working on it and we should have a fix out ASAP.

Closing this as a duplicate of projectcalico/calico-cni#171.

**Closed by fasaxc** 2016-09-12 08:05 UTC
Labels: duplicate

**Comment by gosuri** [comment] 2016-09-12 09:24
Great. Thanks. Looking forward to testing the update!
