### ISSUE TITLE
calico-node fails to start when using ETCD_AUTHORITY=localhost:2379 and hostname is set to localhost

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico-containers#906] opened 2016-04-05 17:56 UTC
I'm trying to run a Kubenetes master using the cloud-config from the the Vagrant demo (https://github.com/projectcalico/calico-containers/tree/master/docs/cni/kubernetes/vagrant-coreos/cloud-config), but modified to use Kubenetes 1.2.0 and calico 0.18.

The master is failing to start - the relevant logs appear to be:

```
Apr 05 17:51:44 localhost calicoctl[16945]: Running Docker container with the following command:
Apr 05 17:51:44 localhost calicoctl[16945]: docker run --restart=always --net=host --privileged --name=calico-node -e HOSTNAME=localhost -e IP=172.24.176.38 -e IP6= -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=localhost:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico calico/node:v0.18.0
Apr 05 17:51:44 localhost calicoctl[16945]: Calico node is running with id: 12cdb4a9fc1ed443da0cc7df5a32a00f590cb29c81c694576ff74881b0725b60
Apr 05 17:51:44 localhost calicoctl[16945]: Waiting for successful startup
Apr 05 17:51:44 localhost calicoctl[16945]: Traceback (most recent call last):
Apr 05 17:51:44 localhost calicoctl[16945]: File "startup.py", line 295, in <module>
Apr 05 17:51:44 localhost calicoctl[16945]: main()
Apr 05 17:51:44 localhost calicoctl[16945]: File "startup.py", line 251, in main
Apr 05 17:51:44 localhost calicoctl[16945]: warn_if_hostname_conflict(ip)
Apr 05 17:51:44 localhost calicoctl[16945]: File "startup.py", line 192, in warn_if_hostname_conflict
Apr 05 17:51:44 localhost calicoctl[16945]: current_ipv4, _ = client.get_host_bgp_ips(hostname)
Apr 05 17:51:44 localhost calicoctl[16945]: File "/usr/lib/python2.7/site-packages/pycalico/datastore.py", line 132, in wrapped
Apr 05 17:51:44 localhost calicoctl[16945]: "running?" % (fn.__name__, e.message))
Apr 05 17:51:44 localhost calicoctl[16945]: pycalico.datastore_errors.DataStoreError: get_host_bgp_ips: Error accessing etcd (Connection to etcd failed due to MaxRetryError("HTTPConnectionPool(host='localhost', port=2379): Max retries exceeded with url: /v2/keys/calico/bgp/v1/host/localhost/ip_addr_v4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70f88882d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))",)).  Is etcd running?
Apr 05 17:51:44 localhost calicoctl[16945]: Calico node failed to start
```

If I run `calicoctl node` it seems to work:

```
core@localhost ~ $ sudo calicoctl node
Running Docker container with the following command:
docker run -d --restart=always --net=host --privileged --name=calico-node -e HOSTNAME=localhost -e IP= -e IP6= -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico calico/node:v0.18.0
Calico node is running with id: 4a2274e837104c5ef9e81aecd228924a816d1823787abe094d23ab932ee5ba2a
Waiting for successful startup
No IP provided. Using detected IP: 172.24.176.38
Calico node started successfully
```

And the difference between the two seems to be the use of ETCD_AUTHORITY=127.0.0.1:2379 in the working case.

**Comment by lwr20** [comment] 2016-04-05 18:15
I've tried changing the hostname with `hostnamectl <name>` and rebooted the master.  I'm still getting the same calico-node error.

**Comment by tomdee** [comment] 2016-04-05 19:31
The following command works for me `docker run --net=host --privileged --rm -e HOSTNAME=localhost -e IP=172.24.176.38 -e IP6= -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=localhost:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico calico/node:v0.18.0`

Can you confirm that a simple ping works? `docker run --net=host --privileged --rm -e HOSTNAME=localhost -e IP=172.24.176.38 -e IP6= -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=localhost:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v /var/run/calico:/var/run/calico calico/node:v0.18.0 ping localhost
`

If so, then the issue is probably somewhere in python or urllib3
`Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70f88882d0>: Failed to establish a new connection: [Errno -2] Name does not resolve',))",)).`

**Comment by fasaxc** [comment] 2016-04-06 07:59
Can we at least detect this case and print a warning from calicoctl.  Feels sufficiently obscure to diagnose that errorring out might be the right approach.

**Comment by padgyx** [comment] 2016-04-27 18:06
Our company is evaluating Calico currently, but calico node we pulled down does not work. 
We have to switch to weave. Below is the error we got:

Pulling Docker image calico/node:latest

Running Docker container with the following command:

docker run -d --restart=always --net=host --privileged --name=calico-node -e HOSTNAME=ip-10-224-15-53.aws.domainname.comec2.internal -e IP= -e IP6= -e CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=127.0.0.1:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v /lib/modules:/lib/modules -v /var/run/calico:/var/run/calico calico/node:latest

Calico node is running with id: 32334c6563a91c627e80ee10eb003f26378b5559e935865ee1af54243330c32e
Waiting for successful startup
No IP provided. Using detected IP: 10.224.15.53
Traceback (most recent call last):
  File "startup.py", line 310, in <module>
    main()
  File "startup.py", line 264, in main
    f.write("IP=" + ip)
  File "/usr/lib/python2.7/site-packages/netaddr/ip/__init__.py", line 421, in __add__
    new_value = int(self._value + num)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
Calico node failed to start

**Comment by caseydavenport** [comment] 2016-04-27 18:17
@padgyx it looks like the issue you're seeing is different from the one @lwr20 was seeing.  Could you open a separate issue for it?

I'd also recommend trying one of our released calico/node images.  The latest is `v0.19.0`.  The `latest` tag is built from master and is not always stable.

**Comment by padgyx** [comment] 2016-04-28 00:21
Thanks for the quick reply. The problem is when user run calicoctl node
command, it will pick up the latest version of calico node image. We have
no way to tell what version of image to use. I have tried the docker run
like this:

sudo docker run -d --restart=always --net=host --privileged
--name=calico-node -e
HOSTNAME=ip-10-224-15-36.aws.domainname.comec2.internal -e IP= -e IP6= -e
CALICO_NETWORKING=true -e AS= -e NO_DEFAULT_POOLS= -e ETCD_AUTHORITY=
127.0.0.1:2379 -e ETCD_SCHEME=http -v /var/log/calico:/var/log/calico -v
/lib/modules:/lib/modules -v /var/run/calico:/var/run/calico
calico/node:v0.9.0


but it does not work. It complains the BGP is not configured
properly: calico KeyError: 'BGP configuration for host not found'

**Comment by fasaxc** [comment] 2016-04-28 07:52
@padgyx if you're using a released version of `calicoctl node` then it fixes the version of the docker image to be the same version as `calicoctl`.  If you build `calicoctl` yourself from master then it pulls `calico/node:latest`.

I think there's a typo in your docker run command above, looks like you've got `v0.9.0` rather than `v0.19.0`, which is current.

**Comment by matthewdupre** [comment] 2016-09-16 21:55
It's wrong to use 'localhost' as the HOSTNAME (certainly if there's more than one node).

The best place to get calicoctl from is the Releases page on github (https://github.com/projectcalico/calico-containers/releases).  This should avoid problems with master not always being stable.

**Comment by caseydavenport** [comment] 2016-11-10 06:42
@matthewdupre @lwr20 what's up with this guy?

**Comment by lwr20** [comment] 2016-11-10 11:35
I'm waiting for a diags fix - as @fasaxc says: "Can we at least detect this case and print a warning from calicoctl. Feels sufficiently obscure to diagnose that errorring out might be the right approach."

**Comment by caseydavenport** [comment] 2016-12-13 07:49
I'm closing this as wontfix.

**Closed by caseydavenport** 2016-12-13 07:49 UTC
Labels: kind/bug, priority/P3, wontfix
