### ISSUE TITLE
used k8s and calico cni plugin

### ISSUE THREAD

**Issue by swqmaven** [projectcalico/calico-containers#1217] opened 2016-10-17 14:39 UTC
deploy successful! but in k8s node calico node is not unhealthy! 
the following log

```
Calico node started successfully
bird: Unable to open configuration file /etc/calico/confd/config/bird6.cfg: No such file or directory
bird: Unable to open configuration file /etc/calico/confd/config/bird.cfg: No such file or directory
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: INFO Backend set to etcd
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: INFO Starting confd
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: INFO Backend nodes set to http://192.168.199.153:2379
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resources from confdir /etc/calico/confd
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird.toml.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird6.toml.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird6_aggr.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird6_ipam.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird_aggr.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/bird_ipam.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/custom_filters.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/custom_filters6.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: DEBUG Loading template resource from /etc/calico/confd/conf.d/tunl-ip.toml
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: ERROR 501: All the given peers are not reachable (failed to propose on members [http://0.0.0.0:2379] twice [last error: Get http://0.0.0.0:2379/v2/keys/calico/ipam/v2/host/k8s-testnode.com/ipv4/block?quorum=false&recursive=true&sorted=false: dial tcp 0.0.0.0:2379: connection refused]) [0]
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: ERROR 501: All the given peers are not reachable (failed to propose on members [http://0.0.0.0:2379] twice [last error: Get http://0.0.0.0:2379/v2/keys/calico/v1/ipam/v4?quorum=false&recursive=true&sorted=false: dial tcp 0.0.0.0:2379: connection refused]) [0]
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: ERROR 501: All the given peers are not reachable (failed to propose on members [http://0.0.0.0:2379] twice [last error: Get http://0.0.0.0:2379/v2/keys/calico/bgp/v1/global/custom_filters?quorum=false&recursive=true&sorted=false: dial tcp 0.0.0.0:2379: connection refused]) [0]
2016-10-17T14:29:36Z k8s-testnode.com confd[50]: ERROR 501: All the given peers are not reachable (failed to propose on members [http://0.0.0.0:2379] twice [last error: Get http://0.0.0.0:2379/v2/keys/calico/bgp/v1/global/custom_filters?quorum=false&recursive=true&sorted=false: dial tcp 0.0.0.0:2379: connection refused]) [0]
```

```
[root@k8s-mater calico]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE
kube-system   agent-192.168.199.132                     1/1       Running   0          5m
kube-system   agent-192.168.199.153                     1/1       Running   0          17m
kube-system   calico-node-f1zn6                         2/2       Running   0          16m
kube-system   calico-node-u2f2t                         2/2       Running   0          5m
kube-system   calico-policy-controller-9wcga            1/1       Running   0          16m
kube-system   etcd-192.168.199.153                      1/1       Running   0          17m
kube-system   k8s-proxy-192.168.199.132                 1/1       Running   0          5m
kube-system   k8s-proxy-192.168.199.153                 1/1       Running   0          17m
kube-system   kube-apiserver-192.168.199.153            1/1       Running   0          17m
kube-system   kube-controller-manager-192.168.199.153   1/1       Running   0          17m
kube-system   kube-dns-v20-5ah2x                        3/3       Running   0          16m
kube-system   kube-scheduler-192.168.199.153            1/1       Running   0          17m
```

thanks for help!

**Comment by caseydavenport** [comment] 2016-10-21 15:40
> All the given peers are not reachable (failed to propose on members [http://0.0.0.0:2379]

Could you share the manifest you're using to deploy? It looks like confd is trying to access etcd on `0.0.0.0` and is failing.  What have you set your etcd_endpoints to?

**Comment by caseydavenport** [comment] 2016-10-26 23:09
@swqmaven Could you check the values you're passing to `--advertise-client-urls` and `-initial-cluster` when starting etcd?

I recently saw this occur when `0.0.0.0` was passed for those flags, when etcd is actually expecting a resolvable IP address / hostname.

**Comment by stresler** [comment] 2016-10-26 23:10
I had something very similar to this and @caseydavenport helped me in slack to realize I'd mis-set several parameters in my etcd config leaving it in a state where I could connect via curl, but confd's usage of it failed. Check that your etcd is started with something very similar to this: 

https://coreos.com/etcd/docs/latest/docker_guide.html

``
docker run -d -v /usr/share/ca-certificates/:/etc/ssl/certs -p 4001:4001 -p 2380:2380 -p 2379:2379 \
 --name etcd quay.io/coreos/etcd \
 -name etcd0 \
 -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
 -initial-advertise-peer-urls http://${HostIP}:2380 \
 -listen-peer-urls http://0.0.0.0:2380 \
 -initial-cluster-token etcd-cluster-1 \
 -initial-cluster etcd0=http://${HostIP}:2380 \
 -initial-cluster-state new
``

**Comment by caseydavenport** [comment] 2016-11-04 05:41
Closing - the issue is a result of an incorrectly configured etcd cluster.

**Closed by caseydavenport** 2016-11-04 05:41 UTC
Labels: kind/support
