### ISSUE TITLE
Include libnetwork to calico/node container

### ISSUE THREAD

**Issue by gunjan5** [projectcalico/calico-containers#1154] opened 2016-09-14 22:59 UTC
- [ ] make libnetwork-plugin pip install-able
- [ ] check if `--libnetwork` flag is passed (for backwards compatiblity) 
- [ ] check for `CALICO_LIBNETWORK_ENABLED` env var

**Comment by tomdee** [comment] 2016-09-15 00:23
Are we sure that we need to check the `--libnetwork` flag at all?
Isn't `CALICO_LIBNETWORK_ENABLED` an environment variable?

**Comment by gunjan5** [comment] 2016-09-15 16:32
@tomdee yes, `CALICO_LIBNETWORK_ENABLED` is env var, fixed the description

For checking the `--libnetwork`, do we honor the flag or keep it for backwards compatibility but ignore it? CC @robbrockbank

**Comment by matthewdupre** [comment] 2016-09-16 19:39
Duplicate of #1003

**Closed by matthewdupre** 2016-09-16 19:39 UTC
Labels: integration/libnetwork, priority/P1

**Comment by gunjan5** [comment] 2016-09-30 18:11
Fix in #1180
