### ISSUE TITLE
can not start the mesos slave service

### ISSUE THREAD

**Issue by ShanshanHe** [projectcalico/calico-containers#649] opened 2015-11-24 01:43 UTC
I followed the instructions to spin up my mesos cluster with calico net-module on two VMs (CentOS7), and I have my master service running, the problem is that I can't start the slave service. Here is the output of $systemctl status mesos-slave.service: 

mesos-slave.service - Mesos Slave
   Loaded: loaded (/usr/lib/systemd/system/mesos-slave.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2015-11-23 20:37:55 EST; 4s ago
  Process: 4194 ExecStart=/usr/bin/mesos-init-wrapper slave (code=exited, status=1/FAILURE)
 Main PID: 4194 (code=exited, status=1/FAILURE)

Nov 23 20:37:55 osboxes mesos-slave[4201]: sandbox is mapped to.
Nov 23 20:37:55 osboxes mesos-slave[4201]: (default: /mnt/mesos/sandbox)
Nov 23 20:37:55 osboxes mesos-slave[4201]: --slave_subsystems=VALUE                          List of comma-separated cgroup subsystems to run the slave binary
Nov 23 20:37:55 osboxes mesos-slave[4201]: in, e.g., 'memory,cpuacct'. The default is none.
Nov 23 20:37:55 osboxes mesos-slave[4201]: Present functionality is intended for resource monitoring and
Nov 23 20:37:55 osboxes mesos-slave[4201]: no cgroup limits are set, they are inherited from the root mesos
Nov 23 20:37:55 osboxes mesos-slave[4201]: cgroup.
Nov 23 20:37:55 osboxes mesos-slave[4201]: --[no-]strict                                     If strict=true, any and all recovery errors are considered fatal.
Nov 23 20:37:55 osboxes mesos-slave[4201]: If strict=false, any expected errors (e.g., slave cannot recover
Nov 23 20:37:55 osboxes mesos-slave[4201]: information about an executor, because the slave died right before

Did I miss anything? any ideas about how to solve this problem?

**Comment by djosborne** [comment] 2015-11-24 18:13
Hi @ShanshanHe . Which instructions did you follow to install core Mesos + Netmodules? Was it the [RPM guide](https://github.com/projectcalico/calico-docker/blob/master/docs/mesos/RpmInstallMesos.md)? And can you rerun the command with the `-l` option: `systemctl status mesos-slave.service -l`

**Comment by djosborne** [comment] 2015-12-07 22:36
@ShanshanHe can you provide some more information to debug this?

**Comment by ShanshanHe** [comment] 2015-12-08 01:29
Hi @djosborne, yeah I followed the  [RPM guide](https://github.com/projectcalico/calico-docker/blob/master/docs/mesos/RpmInstallMesos.md) to install mesos+netmodules, I actually followed the [four step instructions](https://github.com/projectcalico/calico-docker/tree/master/docs/mesos),  `systemctl status mesos-slave.service -l` didn't give me much things, almost the same as the infomation I posted above, but `journalctl -u mesos-slave.service > slave.log` gave me some useful information (this is only part of the log file, let me know if you need full log file) as below, it shows that the slave service fail to load the modules.json of which the content is exactly the same as the post in [Manually Install Calico Networking in Mesos](https://github.com/projectcalico/calico-docker/blob/master/docs/mesos/ManualInstallCalico.md):

```
-- Logs begin at Mon 2015-12-07 19:17:06 EST, end at Mon 2015-12-07 20:09:50 EST. --
Dec 07 19:17:19 osboxes systemd[1]: Starting Mesos Slave...
Dec 07 19:17:19 osboxes systemd[1]: Started Mesos Slave.
Dec 07 19:17:21 osboxes systemd[1]: mesos-slave.service: main process exited, code=exited, status=1/FAILURE
Dec 07 19:17:21 osboxes systemd[1]: Unit mesos-slave.service entered failed state.
Dec 07 19:17:21 osboxes mesos-slave[1372]: Failed to load flag 'modules': Failed to load value 'file:///calico/modules.json': syntax error at line 5 near: # Point Mesos to location of the network-isolator plugin libraries
Dec 07 19:17:21 osboxes mesos-slave[1372]: 
Dec 07 19:17:21 osboxes mesos-slave[1372]: Usage: mesos-slave [options]
Dec 07 19:17:21 osboxes mesos-slave[1372]: 
Dec 07 19:17:21 osboxes mesos-slave[1372]: --appc_store_dir=VALUE                            Directory the appc provisioner will store images in. (default: /tmp/mesos/store/appc)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --attributes=VALUE                                Attributes of machine, in the form:
Dec 07 19:17:21 osboxes mesos-slave[1372]: rack:2 or 'rack:2;u:1'
Dec 07 19:17:21 osboxes mesos-slave[1372]: --authenticatee=VALUE                             Authenticatee implementation to use when authenticating against the
Dec 07 19:17:21 osboxes mesos-slave[1372]: master. Use the default 'crammd5', or
Dec 07 19:17:21 osboxes mesos-slave[1372]: load an alternate authenticatee module using --modules. (default: crammd5)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --[no-]cgroups_cpu_enable_pids_and_tids_count     Cgroups feature flag to enable counting of processes and threads
Dec 07 19:17:21 osboxes mesos-slave[1372]: inside a container.
Dec 07 19:17:21 osboxes mesos-slave[1372]: (default: false)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --[no-]cgroups_enable_cfs                         Cgroups feature flag to enable hard limits on CPU resources
Dec 07 19:17:21 osboxes mesos-slave[1372]: via the CFS bandwidth limiting subfeature.
Dec 07 19:17:21 osboxes mesos-slave[1372]: (default: false)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --cgroups_hierarchy=VALUE                         The path to the cgroups hierarchy root
Dec 07 19:17:21 osboxes mesos-slave[1372]: (default: /sys/fs/cgroup)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --[no-]cgroups_limit_swap                         Cgroups feature flag to enable memory limits on both memory and
Dec 07 19:17:21 osboxes mesos-slave[1372]: swap instead of just memory.
Dec 07 19:17:21 osboxes mesos-slave[1372]: (default: false)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --cgroups_root=VALUE                              Name of the root cgroup
Dec 07 19:17:21 osboxes mesos-slave[1372]: (default: mesos)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --container_disk_watch_interval=VALUE             The interval between disk quota checks for containers. This flag is
Dec 07 19:17:21 osboxes mesos-slave[1372]: used for the 'posix/disk' isolator. (default: 15secs)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --containerizer_path=VALUE                        The path to the external containerizer executable used when
Dec 07 19:17:21 osboxes mesos-slave[1372]: external isolation is activated (--isolation=external).
Dec 07 19:17:21 osboxes mesos-slave[1372]: --containerizers=VALUE                            Comma separated list of containerizer implementations
Dec 07 19:17:21 osboxes mesos-slave[1372]: to compose in order to provide containerization.
Dec 07 19:17:21 osboxes mesos-slave[1372]: Available options are 'mesos', 'external', and
Dec 07 19:17:21 osboxes mesos-slave[1372]: 'docker' (on Linux). The order the containerizers
Dec 07 19:17:21 osboxes mesos-slave[1372]: are specified is the order they are tried
Dec 07 19:17:21 osboxes mesos-slave[1372]: (--containerizers=mesos).
Dec 07 19:17:21 osboxes mesos-slave[1372]: (default: mesos)
Dec 07 19:17:21 osboxes mesos-slave[1372]: --credential=VALUE                                Either a path to a text with a single line
```

**Comment by djosborne** [comment] 2015-12-08 16:43
So the problem is this line:
```
Dec 07 19:17:21 osboxes mesos-slave[1372]: Failed to load flag 'modules': Failed to load value 'file:///calico/modules.json': syntax error at line 5 near: # Point Mesos to location of the network-isolator plugin libraries
```
And the failure is a bit embarrassing on our part - the modules.json file provided in the rpm has "comments" in it, but there's no such thing as a JSON comment. So if you delete the lines beginning with `#` in `/calico/modules.json` you should see some better results.

**Comment by ShanshanHe** [comment] 2015-12-09 00:45
I followed the [manually install instruction](https://github.com/projectcalico/calico-docker/blob/master/docs/mesos/ManualInstallCalico.md) where I downloaded the binary `calico_mesos` and created the modules.json file by copying the content in the [manually install instruction](https://github.com/projectcalico/calico-docker/blob/master/docs/mesos/ManualInstallCalico.md) (which has no lines beginning with `#`) .

**Comment by djosborne** [comment] 2015-12-09 00:51
Can you post your `modules.json` file, by running `cat /calico/modules.json` on your slave?

**Comment by robbrockbank** [comment] 2016-02-05 01:25
@ShanshanHe - Looks like Dan has supplied a fix here.  Closing this issue.  Please re-open if this is still a problem.

**Closed by robbrockbank** 2016-02-05 01:25 UTC
Labels: mesos
