### ISSUE TITLE
Calico Node/Bird routes through default interface(eth0) and not tunnelled interface (tunl0)

### ISSUE THREAD

**Issue by ajays20078** [projectcalico/calico-containers#772] opened 2016-01-31 00:33 UTC
How did i notice the issue -

docker instance on Machine1 was not able to communicate with docker instance on Machine2 inspite of they being part of same profile and the profile had default settings which is allow all communication within the profile.

Background:

I was running a few docker instances on Machine 1(192.168.0.12 , 13 and 14) and they were part of same profile so obviously as expected they were able to communicate with each other.

Now i configured calico on another machine(Machine 2) and created a new docker instance (192.168.0.15) and adding it to same profile as the above mentioned docker instances, But now the docker instances on Machine1 were not able to reach instances on Machine2 and viceversa.

ip route show output from both boxes:

**Machine 1: **
default via 172.31.16.1 dev eth0  
10.0.3.0/24 dev lxcbr0  proto kernel  scope link  src 10.0.3.1  
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1  
172.18.0.0/16 dev docker_gwbridge  proto kernel  scope link  src 172.18.0.1  
172.31.16.0/20 dev eth0  proto kernel  scope link  src 172.31.27.45  
blackhole 192.168.0.0/26  proto bird  
192.168.0.12 dev calie8beb266c79  scope link  
192.168.0.13 dev caliefab0610c79  scope link  
192.168.0.14 dev calif2c7a52ec79  scope link  
192.168.0.15 via 172.31.29.77 dev tunl0  proto bird onlink  
192.168.0.64/26 via 172.31.29.77 dev tunl0  proto bird onlink 

**Machine 2: **
default via 172.31.16.1 dev eth0  
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1  
172.31.16.0/20 dev eth0  proto kernel  scope link  src 172.31.29.77  
192.168.0.0/26 via 172.31.27.45 dev eth0  proto bird  
192.168.0.15 dev cali7fcbe484c7a  scope link  
blackhole 192.168.0.64/26  proto bird 

As we can see on machine 2 192.168.0.0/26 is being routed from interface eth0 and with bird proto, so obviously calico must have configured it, which is the bug! it should have configured it on tunl0 interface which was up and running on Machine 2.

tunl0     Link encap:IPIP Tunnel  HWaddr    
          inet addr:192.168.0.64  Mask:255.255.255.255 
          UP RUNNING NOARP  MTU:1440  Metric:1 
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:0  
          RX bytes:0 (0.0 B)  TX bytes:336 (336.0 B) 

I tried a few silly things to fix it like removing tunl0 interface and restarting calico node on Machine 2, but none of them helped.So finally i manually deleted the route entry for 192.168.0.0/26 from the route table on Machine2 and bingo! , it learned the new route through tunl0 and the instances were now able to communicate. 

ip route show on Machine 2:

default via 172.31.16.1 dev eth0 
10.0.3.0/24 dev lxcbr0  proto kernel  scope link  src 10.0.3.1 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1 
172.31.16.0/20 dev eth0  proto kernel  scope link  src 172.31.29.77 
192.168.0.0/26 via 172.31.27.45 dev tunl0  proto bird onlink 
192.168.0.16 dev calie209b94cc7a  scope link 
blackhole 192.168.0.64/26  proto bird 

So shouldnt the bird have configured proper route through tunl0 initially and not through eth0. If the bird dint do it then shouldnt bird be flushing the wrong entries after creating the new interface so the new routes can be learned?

**Comment by matthewdupre** [comment] 2016-01-31 00:41
One additional bit of background from IRC: this was libnetwork with default (non-calico) IPAM.

**Comment by ajays20078** [comment] 2016-02-01 13:16
More info on this issue.

I noticed the tunl0 link on Machine 2 stops routing (routes are present in route table, output of ip route show is shown below) after sometime(not sure what causes this behaviour), then once your clear the route for the subnet, and ping tunl0 ip from any other machine, it re-learns the route(same route) and starts working.

default via 172.31.16.1 dev eth0 
10.0.0.0/26 via 172.31.27.45 dev eth0  proto bird 
10.0.3.0/24 dev lxcbr0  proto kernel  scope link  src 10.0.3.1 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1 
172.31.16.0/20 dev eth0  proto kernel  scope link  src 172.31.29.77 
192.168.0.0/26 via 172.31.27.45 dev tunl0  proto bird onlink 
192.168.0.16 dev calie209b94cc7a  scope link 
blackhole 192.168.0.64/26  proto bird 
192.168.0.128/26 via 172.31.26.217 dev tunl0  proto bird onlink

**Comment by robbrockbank** [comment] 2016-02-01 19:24
@tomdee Is this possibly the same as #716?

**Comment by robbrockbank** [comment] 2016-02-05 03:54
@ajays20078 Can you paste in the docker run commands you were using to start your containers?  Could you also paste in the output from running `calicoctl pool show`.

**Comment by matthewdupre** [comment] 2016-02-09 15:45
From IRC log: 

    calicoctl pool show
    | IPv4 CIDR    |      Options      |
    | 192.168.0.0/16 | ipip,nat-outgoing |

**Comment by matthewdupre** [comment] 2016-02-09 15:48
I'm not sure what the `docker run`s looked like (I didn't ask at the time: is this a good question to ask people in general?), but it can't have been all bad (since things worked with a bit of tunl0 route prodding).

**Comment by matthewdupre** [comment] 2016-02-09 16:25
I had a quick go at reproing this.  tl;dr: it looks like we don't cope with turning IPIP on for existing pools.  This sounds bad to me: @robbrockbank to prioritise.

I had a Calico Kubernetes setup (installed a couple of weeks ago with the latest version) which wasn't using IPIP; it had the default pool setup with some workloads in.

I turned IPIP on (`calicoctl pool add 192.168.0.0/24 --ipip`) and Felix failed to reconfigure the hosts properly.

- The Felixes wrote to log that "Global config value IpInIpEnabled updated.  Felix must be restarted.": fine.
- 2016-02-09 15:55:06,095 [ERROR][1692/4] calico.felix.frules 211: Failed to configure IPIP device, retrying...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/calico/felix/frules.py", line 207, in install_global_rules
    _configure_ipip_device(config)
  File "/usr/lib/python2.7/site-packages/calico/felix/frules.py", line 312, in _configure_ipip_device
    "mode", "ipip"])
  File "/usr/lib/python2.7/site-packages/calico/felix/futils.py", line 340, in check_call
    args, retcode, stdout, stderr, input=input_str)
FailedSystemCall: Failed system call (retcode : 1, args : ('ip', 'tunnel', 'add', 'tunl0', 'mode', 'ipip'))
  stdout  :
  stderr  : add tunnel "tunl0" failed: File exists
  input  : None
- There was no evidence of Felix retrying, and looking at `ip route` later revealed the 192.168.0.0/26 (etc) routes were still going via eth0.  I'm also not convinced that this was important: the tunl0 device was definitely created.
- Deleting the route led to BIRD fixing the routing table and adjusting the 192.168.0.0/26 route to go via tunl0, as it should.

**Comment by matthewdupre** [comment] 2016-02-09 16:31
(It looks from the above like this is definitely a dupe of #716.)

**Comment by tomdee** [comment] 2016-03-09 01:46
Closing as a dupe

**Closed by tomdee** 2016-03-09 01:46 UTC
Labels: Priority: High
