### ISSUE TITLE
error logs: invalid CIDR address: Device "eth0" does not exist

### ISSUE THREAD

**Issue by lwr20** [projectcalico/calico-containers#952] opened 2016-04-28 17:40 UTC
I'm seeing lots of errors in my logs along the lines of:

```kubelet[2320]: E0428 10:30:04.003907    2320 manager.go:309] NetworkPlugin cni failed on the status hook for pod 'getter-kd3x7' - invalid CIDR address: Device "eth0" does not exist.```

I think its benign, but we're hitting quite a few of them.

Using calico-containers v0.19.0 on a CoreOS VM in GCE and K8s v1.2.0.

**Comment by fasaxc** [comment] 2016-05-16 09:17
Dupe of https://github.com/projectcalico/calico-containers/issues/943.  Looks like a benign upstream k8s issue.

**Closed by fasaxc** 2016-05-16 09:17 UTC
Labels: cni
