### ISSUE TITLE
No way to configure MTU, for AWS, for example

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-containers#743] opened 2016-01-15 16:47 UTC
Our [docs](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/AWS.md) currently say that you need to configure the MTU to make AWS perform but they instructions they give are involved and require `nsenter`ing the container.

That's not acceptable!  We need a better way of configuring the MTU.  

A potential customer just hit this in their initial testing, giving a bad impression.

**Comment by fasaxc** [comment] 2016-01-18 11:05
@robbrockbank I think this is with you

**Comment by robbrockbank** [comment] 2016-01-19 18:00
@TrimBiggs Tim - what happened with this one?

**Comment by matthewdupre** [comment] 2016-09-16 21:07
Closing as duplicate of #488.

**Closed by matthewdupre** 2016-09-16 21:07 UTC
Labels: kind/enhancement, MTU, Spec work needed
