### ISSUE TITLE
docker container unable to communicate

### ISSUE THREAD

**Issue by pmann91** [projectcalico/calico-containers#1022] opened 2016-06-16 08:50 UTC
Hi,

I was trying [this example](https://github.com/projectcalico/calico-containers/blob/master/docs/calico-with-docker/docker-network-plugin/ManualSetup.md) of Calico as a Docker network plugin. I have setup the cluster on 3 ubuntu machines. 

When I try to execute ping command, the ping fails with 100% packet loss

```
docker exec workload-D ping -c 4 workload-A.net1
PING workload-A.net1 (192.168.123.64): 56 data bytes

--- workload-A.net1 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```
 
It is able to resolve the ip correctly but unable to send the ping

Following are the details about the environment

Calico version
```
 ./calicoctl version
0.20.0-dev

```

docker version: 1.11 on two machines and 1.10 on third

OS: ubuntu 14.04

```
./calicoctl status
calico-node container is running. Status: Up 57 minutes
Running felix version 1.4.0rc1

IPv4 BGP status
IP: 172.27.59.244    AS Number: 64511 (inherited)
+---------------+-------------------+-------+----------+-------------+
|  Peer address |     Peer type     | State |  Since   |     Info    |
+---------------+-------------------+-------+----------+-------------+
| 172.27.59.232 | node-to-node mesh |   up  | 07:52:20 | Established |
| 172.27.59.141 | node-to-node mesh |   up  | 07:51:51 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
No IPv6 address configured.
```

**Comment by djosborne** [comment] 2016-06-22 20:50
@pmann91 Apologies for the delay in receiving a response. Can you answer a few questions about your deployment:
- Are you seeing ping failures between containers on the same host?
- Are you seeing ping failures between containers on different hosts?
- Who owns the networking fabric between hosts? i.e. are you on private cloud (Amazon, digial ocean, etc.) or private cloud?

**Comment by pmann91** [comment] 2016-06-23 05:22
Hi @djosborne,

- There are no ping failure between containers on the same host
- Ping failure is noticed between containers on different host. The IP of other container is being properly resolved but ping failure is noticed.
- I am working on physical machines i.e., virtual machines

The example works perfectly on vagrant box but when I set up the cluster on my machines its not working. Am I missing something?

**Comment by djosborne** [comment] 2016-06-27 19:34
@pmann91 the most common cause for the scenario you've described is the configuration of the network fabric between hosts. Some public cloud providers configure their network to drop packets with unrecognized src/dest IP. Since Calico does not use encapsulation, container traffic will have src/dest of addresses it has allocated (192.168.0.0/16 - by default).

You mentioned you were on virtual machines, but did not clarify if this bare metal system is on a network which you have full control over. So I can't say for sure if this is the issue you're encountering. 

If it is the cause, you have two options:
1. If you have the option, disable src/dest checks on the networking fabric between hosts.
2. Run calico with ip-over-ip encapsulation by adding a  calico pool with `--ipip` and restarting calico/node on each host.

If this is not the cause, these issues can be easier to debug by going back and forth over our public slack channel: https://slack.projectcalico.org/

**Comment by mattymo** [comment] 2016-06-30 07:22
I'm not sure if this will help, but I'm deploying a similar scenario and have a slightly different issue. It consists of 3 virtual machines on libvirtd and one simple private LAN.

 I can resolve internal DNS and internal TCP works great. ICMP isn't working, but I don't need it. What's stranger is if I have a container with --net=host (also from a bare host it's true), connectivity to containers on different hosts is failing. This doesn't always happen, by the way. It could work 5 times correctly on one bare metal host, work intermittently on another, and another host will always fail. Changing encapsulation options for calico seem to have bad poor results:
--nat-outgoing doesn't change any effect
--ipip never helps my situation
Combined --nat-outgoing and --ipip always results in no possible intercontainer traffic.

@djosborne how would one go about disabling src/dest checks on a libvirt private network?

**Comment by djosborne** [comment] 2016-06-30 22:29
@pmann91 I'm going to close this issue, please follow up on slack if you're still having issues

@mattymo Likely a different issue. Can you open a seperate issue for assistance?

**Closed by djosborne** 2016-06-30 22:29 UTC
Labels: blocked, question
