### ISSUE TITLE
Host cannot communicate with containers when using IP-IP

### ISSUE THREAD

**Issue by slaws** [projectcalico/calico-containers#426] opened 2015-08-06 10:21 UTC
Hello,

I have actually 2 k8s nodes (192.168.112.7 and 192.168.112.10) running containers on subnet 172.17.0.0/16.
This k8s cluster is running on an Openstack tenant (I'm just a user of this tenant).

The pool  172.17.0.0/16 is configured with ipip and nat-outgoing.
The communication between containers on different hosts is working fine.

However hosts cannot communicate with remote containers. Return packets are lost.

After making some tests asked on IRC it seems that return packets are using the wrong interface : 
```
# tcpdump -i tunl0 icmp                                                                                                                    
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on tunl0, link-type RAW (Raw IP), capture size 262144 bytes
09:43:33.992886 IP 192.168.112.7 > 172.17.2.2: ICMP echo request, id 13435, seq 145, length 64
09:43:34.993046 IP 192.168.112.7 > 172.17.2.2: ICMP echo request, id 13435, seq 146, length 64
09:43:35.992981 IP 192.168.112.7 > 172.17.2.2: ICMP echo request, id 13435, seq 147, length 64
09:43:36.993017 IP 192.168.112.7 > 172.17.2.2: ICMP echo request, id 13435, seq 148, length 64
^C

# tcpdump -i eth0 icmp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
09:43:54.993062 IP 172.17.2.2 > 192.168.112.7: ICMP echo reply, id 13435, seq 166, length 64
09:43:55.992958 IP 172.17.2.2 > 192.168.112.7: ICMP echo reply, id 13435, seq 167, length 64
09:43:56.993048 IP 172.17.2.2 > 192.168.112.7: ICMP echo reply, id 13435, seq 168, length 64
09:43:57.992968 IP 172.17.2.2 > 192.168.112.7: ICMP echo reply, id 13435, seq 169, length 64
^C
```

Is there a way to work around this ?

**Comment by fasaxc** [comment] 2015-08-06 13:06
This is a bit sad.  We need packets from containers to hosts to be sent using IPIP but packets from host to host to be sent normally.  The standard routing table doesn't seem to support routing based on source address so we probably need to use iptables to pick out those packets and redirect them to tuml0.

**Comment by fasaxc** [comment] 2015-08-06 13:17
Looks like to redirect packets we need multiple routing tables, with iptables marking packets for forwarding by different tables.

**Comment by caseydavenport** [comment] 2015-08-06 17:50
Yep, this is a bit sad.

@slaws - Are you certain that IPIP is necessary for your deployment? It appears that your two k8s nodes are on the same /24 subnet.  Do you know what the underlying network looks like?

If your k8s nodes have L2 connectivity, I wouldn't expect IPIP to be required for your deployment.

cc @Symmetric

**Comment by slaws** [comment] 2015-08-06 19:06
@caseydavenport : Since I'm new with openstack (and openstack networks) I'm not certain that IPIP is required.

I also thought that IPIP was not necessary but when I tried to setup calico like I did on bare-metal, neither host nor containers could reach containers on another host.

**Comment by fasaxc** [comment] 2015-08-06 20:00
@slaws @caseydavenport the underlying fabric may be L2 but it appears to be doing a reverse-path check, which will disallow our routed packets (because the source of the packet will be the VM's IP, which is unknown to the fabric).

**Comment by caseydavenport** [comment] 2015-08-06 20:05
@fasaxc By the VMs IP do you mean the the pod's?  Perhaps I am missing something, but I would have thought in this case IPIP is not required, and simply using --nat-outgoing to provide the MASQUERADE rules would work.

**Comment by lxpollitt** [comment] 2015-08-06 22:34
@caseydavenport --nat-outgoing NATs outbound connections from a container.  In this case the connection is from the remote host to the container (i.e. inbound).  The inbound traffic to the container arrives fine.  The outbound traffic from the container gets dropped (presumably because of RPF in the fabric that doesn't recognize the container's IP).  Trying to NAT that traffic wouldn't help because when it got back to the host the host would not recognize it came from the container, I think.

In general to get traffic from a non-IPIP address (whether from the rest of the internet or another host within the data center) you need to provide a NAT rule for the incoming traffic.  There are examples in our GCE and other cloud provider tutorials I believe. 

e.g. `sudo iptables -A PREROUTING -t nat -i ens4v1 -p tcp --dport 80 -j DNAT  --to 192.168.2.1:80`

**Comment by slaws** [comment] 2015-08-07 09:18
Based on @fasaxc comment, I have a (dirty) workaround so I can continue my tests : 

```
# echo '8    docker' >> /etc/iproute2/rt_tables
# ip rule add from 172.17.1.0/24 table docker
# ip route add 192.168.112.0/24 table docker dev tunl0
```
Now I can ping containers on other hosts from a host or a container 
```
# ip r
default via 192.168.112.1 dev eth0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
172.17.1.1 dev cali8ec424503ce  scope link 
172.17.1.2 dev cali8ee3c85a3ce  scope link 
172.17.2.1 via 192.168.112.10 dev tunl0  proto bird onlink 
172.17.2.2 via 192.168.112.10 dev tunl0  proto bird onlink 
172.17.2.3 via 192.168.112.10 dev tunl0  proto bird onlink 
172.17.2.4 via 192.168.112.10 dev tunl0  proto bird onlink 
192.168.112.0/24 dev eth0  proto kernel  scope link  src 192.168.112.7 

# docker exec -it 31b2c9c99743 ping -c4 172.17.2.2
PING 172.17.2.2 (172.17.2.2): 56 data bytes
64 bytes from 172.17.2.2: seq=0 ttl=62 time=1.174 ms
64 bytes from 172.17.2.2: seq=1 ttl=62 time=0.819 ms
64 bytes from 172.17.2.2: seq=2 ttl=62 time=0.706 ms
64 bytes from 172.17.2.2: seq=3 ttl=62 time=0.684 ms

--- 172.17.2.2 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.684/0.845/1.174 ms


# ping -c4 172.17.2.2
PING 172.17.2.2 (172.17.2.2) 56(84) bytes of data.
64 bytes from 172.17.2.2: icmp_seq=1 ttl=63 time=0.802 ms
64 bytes from 172.17.2.2: icmp_seq=2 ttl=63 time=0.471 ms
64 bytes from 172.17.2.2: icmp_seq=3 ttl=63 time=0.580 ms
64 bytes from 172.17.2.2: icmp_seq=4 ttl=63 time=0.629 ms

--- 172.17.2.2 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3000ms
rtt min/avg/max/mdev = 0.471/0.620/0.802/0.121 ms
```

**Comment by TeaBough** [comment] 2015-09-25 15:49
I have the exact same problem with 2 vagrant machines. But your workaround is not working in my case. I have to vm : 192.168.31.51 / 192.168.31.52 and the calico subnet is : 192.168.0.0/16.
So I did : 
   
    # echo '8    docker' >> /etc/iproute2/rt_tables
    # ip rule add from 192.168.0.0/16 table docker
    # ip route add 192.168.31.0/24 table docker dev tunl0

I did the same thing on both of my machine ...

**Comment by slaws** [comment] 2015-09-25 16:25
@TeaBough I didn't test using vagrant and virtualbox.
However, with these rules and some iptables rules to avoid masquerading it seems to work on openstack.
I use these (basic) iptables rules to prevent masquerading when packets from containers are going to another container or a host : 
```
# iptables -t nat -N EXTERNAL
# iptables -t nat -A POSTROUTING -j EXTERNAL
# iptables -t nat -A EXTERNAL -s 172.17.0.0/16 -d 172.17.0.0/16 -j RETURN
# iptables -t nat -A EXTERNAL -s 172.17.0.0/16 -d 192.168.112.0/24 -j RETURN
# iptables -t nat -A EXTERNAL -j MASQUERADE
```
And I also have docker masquerading and iptables disabled

**Comment by Symmetric** [comment] 2015-09-25 19:20
@TeaBough I think your problem is that your VM IPs are in your calico subnet. You've created a rule which will push all traffic (from container or host) into the docker table, and that table only has the route `192.168.31.0/24 dev tunl0`.

Try setting your Calico pool to a prefix that doesn't include your VM IPs, say `192.168.32.0/24`. Then use the following route config:

```
# echo '8    docker' >> /etc/iproute2/rt_tables
# ip rule add from 192.168.32.0/24 table docker
# ip route add 192.168.31.0/24 table docker dev tunl0
```

**Comment by TeaBough** [comment] 2015-09-28 12:17
Nothing worked ... I'm now using the Vagrantfile in default-networking/ubuntu : https://github.com/projectcalico/calico-docker/tree/master/docs/getting-started/default-networking/vagrant-ubuntu.

Here is the configuration : 
`172.17.8.101 (calico-01)`
and
`172.17.8.102 (calico-02)`

I have 2 containers :
`workload-A (192.168.0.1) running on calico-01`
`workload-B (192.168.0.2) running on calico-02`

Here is my pool : 
```
root@calico-01:/home/vagrant# calicoctl pool show
+----------------+---------+
|   IPv4 CIDR    | Options |
+----------------+---------+
| 192.168.0.0/16 |         |
+----------------+---------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+
```
Here is my containers : 
```
root@calico-01:/home/vagrant# calicoctl endpoint show --detailed
+-----------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+------------+--------+
|  Hostname | Orchestrator ID |                           Workload ID                            |           Endpoint ID            |   Addresses    |        MAC        |  Profiles  | State  |
+-----------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+------------+--------+
| calico-01 |      docker     | 892ab4927dfb2c910fe0bbbf26e921cdb8bb274645161da43ed237a41dad8f53 | 3a6dd31065b911e5a74e080027c324cc | 192.168.0.1/32 | b6:84:2c:58:bf:e9 | PROF_A_C_E | active |
| calico-02 |      docker     | 12dcb2454858ec87d4e609a4cad950787dd340823756fdfa412af11c380f0283 | 3f6524ea65b911e58efe080027c324cc | 192.168.0.2/32 | 96:8c:96:14:5e:7b | PROF_A_C_E | active |
+-----------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+------------+--------+
```

Here is my route table : 
```
root@calico-01:/home/vagrant# ip r
default via 10.0.2.2 dev eth0
10.0.2.0/24 dev eth0  proto kernel  scope link  src 10.0.2.15
10.1.0.0/16 dev docker0  proto kernel  scope link  src 10.1.42.1
172.17.8.0/24 dev eth1  proto kernel  scope link  src 172.17.8.101
192.168.0.1 dev cali3a6dd31065b  scope link
192.168.0.2 via 172.17.8.102 dev eth1  proto bird
```

I manage to ping `calico-01` from `calico-02`.
If I ping `192.168.0.1` from `calico-02` I get when I `tcpdump -i eth0 icmp` on `calico-01`, I only get the request not the response.

If I `tcpdump -i tunl0 icmp`  I get nothing

**Comment by Symmetric** [comment] 2015-09-28 17:16
Can you show the output of `ip route show table unspec` please? The output above only contains the default table, not the docker table.

**Comment by mzupan** [comment] 2015-09-28 17:39
I'm getting the same issue

```
root@ip-10-122-1-20:~# calicoctl status
calico-node container is running. Status: Up 28 minutes

IPv4 BGP status
+--------------+-------------------+-------+----------+-------------+
| Peer address |     Peer type     | State |  Since   |     Info    |
+--------------+-------------------+-------+----------+-------------+
| 10.122.1.21  | node-to-node mesh |   up  | 17:11:20 | Established |
| 10.122.1.22  | node-to-node mesh |   up  | 17:11:34 | Established |
+--------------+-------------------+-------+----------+-------------+

IPv6 BGP status
+--------------+-----------+-------+-------+------+
| Peer address | Peer type | State | Since | Info |
+--------------+-----------+-------+-------+------+
+---
```

Node1 
  eth0: `10.122.1.21`
  cbr0: `192.168.1.1`

Node2
  eth0: `10.122.1.22`
  cbr0: `192.168.2.1`

From node1 pinging `192.168.2.1` I don't get a response but on node2 i see

```
17:37:34.533602 IP 10.122.1.21 > 10.122.1.22: IP 10.122.1.21 > 192.168.2.1: ICMP echo request, id 16855, seq 653, length 64 (ipip-proto-4)
```



Node1 route table

```
root@ip-10-122-1-21:~# ip route show table unspec
default via 10.122.1.1 dev eth0
10.122.1.0/24 dev eth0  proto kernel  scope link  src 10.122.1.21
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.1.0/24 dev cbr0  proto kernel  scope link  src 192.168.1.1
192.168.2.0/24 via 10.122.1.22 dev tunl0  proto bird onlink
192.168.2.2 via 10.122.1.22 dev tunl0  proto bird onlink
broadcast 10.122.1.0 dev eth0  table local  proto kernel  scope link  src 10.122.1.21
local 10.122.1.21 dev eth0  table local  proto kernel  scope host  src 10.122.1.21
broadcast 10.122.1.255 dev eth0  table local  proto kernel  scope link  src 10.122.1.21
broadcast 127.0.0.0 dev lo  table local  proto kernel  scope link  src 127.0.0.1
local 127.0.0.0/8 dev lo  table local  proto kernel  scope host  src 127.0.0.1
local 127.0.0.1 dev lo  table local  proto kernel  scope host  src 127.0.0.1
broadcast 127.255.255.255 dev lo  table local  proto kernel  scope link  src 127.0.0.1
broadcast 172.17.0.0 dev docker0  table local  proto kernel  scope link  src 172.17.42.1
local 172.17.42.1 dev docker0  table local  proto kernel  scope host  src 172.17.42.1
broadcast 172.17.255.255 dev docker0  table local  proto kernel  scope link  src 172.17.42.1
broadcast 192.168.1.0 dev cbr0  table local  proto kernel  scope link  src 192.168.1.1
local 192.168.1.1 dev cbr0  table local  proto kernel  scope host  src 192.168.1.1
broadcast 192.168.1.255 dev cbr0  table local  proto kernel  scope link  src 192.168.1.1
fe80::/64 dev eth0  proto kernel  metric 256  mtu 9001
fe80::/64 dev cbr0  proto kernel  metric 256
unreachable default dev lo  table unspec  proto kernel  metric 4294967295  error -101
local ::1 dev lo  table local  proto none  metric 0
local fe80::8af:26ff:fe78:f98f dev lo  table local  proto none  metric 0
local fe80::20c1:12ff:fea6:5bb dev lo  table local  proto none  metric 0
ff00::/8 dev eth0  table local  metric 256  mtu 9001
ff00::/8 dev cbr0  table local  metric 256
unreachable default dev lo  table unspec  proto kernel  metric 4294967295  error -101
```

Node2 route table

```
root@ip-10-122-1-22:/var/log/calico/kubernetes# ip route show table unspec
default via 10.122.1.1 dev eth0
10.122.1.0/24 dev eth0  proto kernel  scope link  src 10.122.1.22
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1
192.168.1.0/24 via 10.122.1.21 dev tunl0  proto bird onlink
192.168.2.0/24 dev cbr0  proto kernel  scope link  src 192.168.2.1
192.168.2.2 dev cali746d84b0660  scope link
broadcast 10.122.1.0 dev eth0  table local  proto kernel  scope link  src 10.122.1.22
local 10.122.1.22 dev eth0  table local  proto kernel  scope host  src 10.122.1.22
local 10.122.1.22 dev cali746d84b0660  table local  proto kernel  scope host  src 10.122.1.22
broadcast 10.122.1.255 dev eth0  table local  proto kernel  scope link  src 10.122.1.22
broadcast 127.0.0.0 dev lo  table local  proto kernel  scope link  src 127.0.0.1
local 127.0.0.0/8 dev lo  table local  proto kernel  scope host  src 127.0.0.1
local 127.0.0.1 dev lo  table local  proto kernel  scope host  src 127.0.0.1
broadcast 127.255.255.255 dev lo  table local  proto kernel  scope link  src 127.0.0.1
broadcast 172.17.0.0 dev docker0  table local  proto kernel  scope link  src 172.17.42.1
local 172.17.42.1 dev docker0  table local  proto kernel  scope host  src 172.17.42.1
broadcast 172.17.255.255 dev docker0  table local  proto kernel  scope link  src 172.17.42.1
broadcast 192.168.2.0 dev cbr0  table local  proto kernel  scope link  src 192.168.2.1
local 192.168.2.1 dev cbr0  table local  proto kernel  scope host  src 192.168.2.1
broadcast 192.168.2.255 dev cbr0  table local  proto kernel  scope link  src 192.168.2.1
fe80::/64 dev eth0  proto kernel  metric 256  mtu 9001
fe80::/64 dev cbr0  proto kernel  metric 256  mtu 9001
fe80::/64 dev cali746d84b0660  proto kernel  metric 256
unreachable default dev lo  table unspec  proto kernel  metric 4294967295  error -101
local ::1 dev lo  table local  proto none  metric 0
local fe80::828:a1ff:fec4:ef1f dev lo  table local  proto none  metric 0
local fe80::2c7d:1eff:fe92:1b6b dev lo  table local  proto none  metric 0
local fe80::7cd2:cbff:fe61:133f dev lo  table local  proto none  metric 0
ff00::/8 dev eth0  table local  metric 256  mtu 9001
ff00::/8 dev cbr0  table local  metric 256  mtu 9001
ff00::/8 dev cali746d84b0660  table local  metric 256
unreachable default dev lo  table unspec  proto kernel  metric 4294967295  error -101
```


node1 ip rule list

```
root@ip-10-122-1-21:~# ip rule list
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default
```

node2 ip rule list

```
root@ip-10-122-1-22:/var/log/calico/kubernetes#  ip rule list
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default
```

**Comment by Symmetric** [comment] 2015-09-28 17:49
@mzupan can you try the workaround posted above, on each node:

```
# echo '8    docker' >> /etc/iproute2/rt_tables
# ip rule add from <cbr0 CIDR> table docker
# ip route add <nodes subnet> table docker dev tunl0
```

And let me know if it works for you? We're looking at a longer-term fix, but I believe this should get things working. (This is an ip-in-ip specific issue, so it's only required in cloud environments).

**Comment by TeaBough** [comment] 2015-09-28 20:02
```
root@calico-01:/home/vagrant# ip route show table unspec
172.17.8.0/24 dev tunl0  table docker  scope link 
default via 10.0.2.2 dev eth0 
10.0.2.0/24 dev eth0  proto kernel  scope link  src 10.0.2.15 
10.1.0.0/16 dev docker0  proto kernel  scope link  src 10.1.42.1 
172.17.8.0/24 dev eth1  proto kernel  scope link  src 172.17.8.101 
192.168.0.1 dev cali908ba72e661  scope link 
192.168.0.2 via 172.17.8.102 dev eth1  proto bird 
broadcast 10.0.2.0 dev eth0  table local  proto kernel  scope link  src 10.0.2.15 
local 10.0.2.15 dev eth0  table local  proto kernel  scope host  src 10.0.2.15 
broadcast 10.0.2.255 dev eth0  table local  proto kernel  scope link  src 10.0.2.15 
broadcast 10.1.0.0 dev docker0  table local  proto kernel  scope link  src 10.1.42.1 
local 10.1.42.1 dev docker0  table local  proto kernel  scope host  src 10.1.42.1 
broadcast 10.1.255.255 dev docker0  table local  proto kernel  scope link  src 10.1.42.1 
broadcast 127.0.0.0 dev lo  table local  proto kernel  scope link  src 127.0.0.1 
local 127.0.0.0/8 dev lo  table local  proto kernel  scope host  src 127.0.0.1 
local 127.0.0.1 dev lo  table local  proto kernel  scope host  src 127.0.0.1 
broadcast 127.255.255.255 dev lo  table local  proto kernel  scope link  src 127.0.0.1 
broadcast 172.17.8.0 dev eth1  table local  proto kernel  scope link  src 172.17.8.101 
local 172.17.8.101 dev eth1  table local  proto kernel  scope host  src 172.17.8.101 
broadcast 172.17.8.255 dev eth1  table local  proto kernel  scope link  src 172.17.8.101 
fe80::/64 dev eth0  proto kernel  metric 256 
fe80::/64 dev eth1  proto kernel  metric 256 
fe80::/64 dev cali908ba72e661  proto kernel  metric 256 
unreachable default dev lo  table unspec  proto kernel  metric 4294967295  error -101
local ::1 dev lo  table local  proto none  metric 0 
local fe80:: dev lo  table local  proto none  metric 0 
local fe80:: dev lo  table local  proto none  metric 0 
local fe80:: dev lo  table local  proto none  metric 0 
local fe80::a00:27ff:fe31:44 dev lo  table local  proto none  metric 0 
local fe80::a00:27ff:fec3:24cc dev lo  table local  proto none  metric 0 
local fe80::109b:d7ff:fee2:f883 dev lo  table local  proto none  metric 0 
ff00::/8 dev eth0  table local  metric 256 
ff00::/8 dev eth1  table local  metric 256 
ff00::/8 dev cali908ba72e661  table local  metric 256 
unreachable default dev lo  table unspec  proto kernel  metric 4294967295  error -101
```

and 

```
root@calico-01:/home/vagrant# ip rule list
0:	from all lookup local 
32765:	from 192.168.0.0/16 lookup docker 
32766:	from all lookup main 
32767:	from all lookup default
```

@Symmetric You were saying that it's an ip-in-ip issue required in cloud environments, but in my case it's when I use Vagrant without the ip-in-ip mode : 

```
root@calico-01:/home/vagrant# calicoctl  pool show
+----------------+---------+
|   IPv4 CIDR    | Options |
+----------------+---------+
| 192.168.0.0/16 |         |
+----------------+---------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+
```

It's when I use this Vagrantfile : https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/default-networking/vagrant-ubuntu/Vagrantfile

**Comment by Symmetric** [comment] 2015-09-28 23:33
@TeaBough Sorry, missed that the first time round. I think you're probably hitting an rp_filter issue. Can you try disabling RPF on the interfaces on the hosts?

Try this:

`for if in all eth1 tunl0; do sudo bash -c "echo 0 > /proc/sys/net/ipv4/conf/${if}/rp_filter"; done`

If that fix works, it's a bug in our Vagrant file. Can you open a separate issue to track that (since this issue is specifically covering a distinct IP-in-IP issue).

**Comment by tomdee** [comment] 2015-11-06 01:21
@Symmetric Can we do anything with this issue? Are we able to test the possible vagrant issue ourselves?

**Comment by tomdee** [comment] 2015-11-19 21:14
@Symmetric @caseydavenport Any update on this kubernetes issue?

**Comment by Symmetric** [comment] 2015-11-19 21:26
@tomdee looks like the Vagrant issue was with our bare calico-docker Vagrantfile, which should be easy to test. The original issue in this thread should be followed up on now -- we were deferring making a fix here until we figured out what our approach was going to be on other cloud providers.

Notes -- @fasaxc suggested that we could add iptables rules equivalent to the `ip rule` here, but in my testing I found that rp_filter didn't work if the `ip rule` wasn't there (IOW there needs to be a valid route for the return packets).

So we'll probably need a new Actor in Felix to keep the `ip rule` entries up to date with the node ipset.

**Comment by Symmetric** [comment] 2015-11-19 21:27
Also this isn't a kubernetes-specific issue; it applies to the bare calico-docker case as well, it's just that nobody has hit it there.

**Comment by dragonde** [comment] 2015-12-03 11:12
I'm experiencing this issue. I deployed k8s over CoreOs nodes running on DigitalOcean (DO).
The hosts network is a DO private net, 10.131.0.0/16, and the pods network 10.2.0.0 corresponding to:

calicoctl pool add 10.2.0.0/16 --ipip --nat-outgoing

I get communication host-to-host and pod-to-pod, but NO comunication "host-to-pod", so kube-proxy, which is a hostNetwork:true container, cannot proxy to containers running in other nodes.

It would be interesting to solve this issue in order to get calico working in cloud deployments.

**Comment by caseydavenport** [comment] 2015-12-03 23:10
To implement this fix, we need to add code to Felix which is aware of which IP addresses are assigned to this host, as well as all node IP addresses in the Calico deployment.

When IPIP is enabled, Felix will need to install the following for each pod IP / subnet on this host, 
```
ip rule add from <Pod IP> table docker
```

Felix will also need to install the following for each node in the Calico deployment.
```
ip route add <node IP> table docker dev tunl0
```

I'd like to start addressing this issue, as a number of users have hit it. @fasaxc - Does the above seem reasonable to add to Felix?

**Comment by spikecurtis** [comment] 2015-12-24 00:21
One further issue rankles this mix:
Using both `ip rule` workaround for node to pod comm interferes with `--nat-outgoing` for pod to node comms.

The issue is that our outgoing NAT is in the `POSTROUTING` hook, so we change the source after the `ip rule` routing has happened, causing a masqueraded packet from the pod to be tunnelled `ipip`.  The host on the other side sees a host-to-host IP packet coming out of the `tunl0` and drops it.

**Comment by fasaxc** [comment] 2016-01-04 17:32
@caseydavenport felix already maintains some useful ipsets that might help.  We have sets for each of:

* all host IPs
* all (IPAM) pool CIDRs
* all CIDRs with NAT turned on.

Should make it easier to match traffic that's going from an IPAM-assigned IP to a host, for example.

We could add an ipset for "all IPIP pool CIDRs" too if that'd help.

**Comment by fasaxc** [comment] 2016-01-04 17:33
Also, you can match packets from pod interfaces with an interface match.  In iptables, we can do "cali*" to refer to all of the itnterfaces, without having to add individual rules.  I'd prefer if we can add a few static rules that take advantage of dynamic ipsets and interface matching, if possible.

**Comment by spikecurtis** [comment] 2016-01-04 17:44
@fasaxc I'm not sure ipsets helps here, unless we do all this in netfilter.  What @caseydavenport proposed is to use `ip rule` (i.e. policy routing), not netfilter.

**Comment by Symmetric** [comment] 2016-01-04 17:59
Not sure if this is what @spikecurtis was referring to, but keep in mind
that if you do the pure iptables route, you'll need to take account of
reverse path filtering (I found that I needed the `ip rule` statement, or
rp_filter=0 for _incoming_ packets to be accepted from another node to a
container). Seems that rp_filter needs there to be some route to the packet
source, though it doesn't need to be the first choice for outgoing packets.

Digging into rp_filter a bit more, it sounds like the behaviour I saw is
actually loose mode filtering (rp_filter=2), not strict mode (rp_filter=1);
from https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt,
```

rp_filter - INTEGER
	0 - No source validation.
	1 - Strict mode as defined in RFC3704 Strict Reverse Path
	    Each incoming packet is tested against the FIB and if the interface
	    is not the best reverse path the packet check will fail.
	    By default failed packets are discarded.
	2 - Loose mode as defined in RFC3704 Loose Reverse Path
	    Each incoming packet's source address is also tested against the FIB
	    and if the source address is not reachable via any interface
	    the packet check will fail.

	Current recommended practice in RFC3704 is to enable strict mode
	to prevent IP spoofing from DDos attacks. If using asymmetric routing
	or other complicated routing, then loose mode is recommended.

```

**Comment by lxpollitt** [comment] 2016-01-04 18:03
Someone recently suggested that you could switch off RPF in AWS and GCE.  Not sure if that is true or not, but we should definitely investigate that too.

**Comment by Symmetric** [comment] 2016-01-04 18:16
I can confirm that there is a per-instance filtering option that can be
disabled on both platforms. E.g.
https://cloud.google.com/compute/docs/networking#canipforward on GCE
(annoyingly only configurable at creation time). Is that what you're
referring to?

**Comment by fasaxc** [comment] 2016-01-05 09:35
@spikecurtis  Sorry, I thought that was something you could do in a rule but I've checked the docs and you definitely can't.  

However, you can match on the FWMARK, which means you can pass a flag from the iptables mangle/PREROUTING chain to the RPDB.  That allows you to do a generic match in iptables based on an ipset and pass the result to the RPDB.  I think that's a better approach than adding lots of rules into the RPDB.  I get the impression that the RPDB is scanned linearly (so it might be slow to have lots of rules) and it's a shared, global resource, which makes it very awkward for felix to manage.

The iptables rule would be something like[1]:
```
iptables -t mangle -A PREROUTING \
    --in-interface cali* \
    --match set --match-set felix-calico-hosts-4 dst \
    --match set ! --match-set felix-masq-ipam-pools src \
    --jump MARK --set-mark 12345
```
which matches packets coming from a non-NATted pod, going to any Calico host and sets a static mark.

Then you can match on it using `ip rule`[2]:
```
ip rule add priority 123 fwmark 12345 table felix-ipip
```
("felix-ipip" seems like a better name than "docker")

Finally, is there a way we can avoid putting an entry in the new routing table for every host?  Could we install a single 0.0.0.0/0 route instead?  The new routing table can only be reached for packets we've already vetting in iptables so we should be able to do something generic there.

[1] elided for readability but we should introduce a felix-PREROUTING chain and put the rule in that rather than hijacking the PREROUTING chain and there are constants in felix for all the ipset names that we need to use.

[2] priority and mark value should be config params.

CC @caseydavenport

**Comment by fasaxc** [comment] 2016-01-05 09:40
@Symmetric Loose mode is no good for us on a host.  We need strict mode to prevent workloads from spoofing other workloads on the same host.  I'm not sure how the RPDB interacts with the RPF check.  We might need to populate the additional routing table with the local workload routes to make this work.

**Comment by caseydavenport** [comment] 2016-01-06 00:16
> https://cloud.google.com/compute/docs/networking#canipforward on GCE

`canIpForward` isn't quite enough though - you also need a GCE route (https://cloud.google.com/compute/docs/networking#addingroute) or else the GCE fabric itself will still RPF your packets.  I've tested this with Calico.  The `canIpForward` option appears to be a separate per-instance RPF, but doesn't disable the RPF in GCE's network.

From my reading of the documentation, I don't see a way to say "don't perform any RPF".  As far as I can tell, you need to program GCE routes to make the fabric aware of your source address ranges.

**Closed** 2016-01-12 01:18 UTC
Labels: bug
