### ISSUE TITLE
Pods get still get old ips assigned

### ISSUE THREAD

**Issue by hanikesn** [projectcalico/calico-containers#779] opened 2016-02-02 14:22 UTC
Steps to reproduce:
1. Create new kubernetes cluster
2. Add ipv4 pool
3. create some pods
4. Delete ipv4 pool
5. create another ipv4 pool
6. create some pods

Expected result new prods from step 6. get ip addresses from the new pool, but they get addresses from the old one. 

https://transfer.sh/I1GYQ/diags-020216-132513.tar.gz

**Comment by tomdee** [comment] 2016-03-09 01:47
Could this be a dupe of #716 ? @caseydavenport Thoughts on this issue?

**Comment by caseydavenport** [comment] 2016-03-09 16:34
I don't think this is related to #716.  This looks like a known IPAM issue with these exact symptoms.

There is a PR which includes the fix open right now - I am in the middle of reviewing.

This guy: https://github.com/projectcalico/libcalico/pull/74

**Comment by robbrockbank** [comment] 2016-03-18 23:37
This should be fixed in the v0.18.0 release of calicoctl which should be available next week.

If you have an existing deployment which is still hitting this issue, upgrade to the new calicoctl when it is out,  add the old IP Pool back in and then delete it again - that will perform all the necessary tidy up of the old pool.

Please re-open if this problem is still occurring with the 0.18.0 release.

**Closed by robbrockbank** 2016-03-18 23:37 UTC
Labels: blocked, kubernetes
