### ISSUE TITLE
calicoctl status is affected by bash 4.3 version

### ISSUE THREAD

**Issue by hectorj2f** [projectcalico/calico-containers#1075] opened 2016-07-22 10:58 UTC
Hello there,

I am using CoreOS `1068.8.0` which uses `bash` version `4.3` on which there is a bug https://bugs.archlinux.org/task/39533. This seems to affect to the output of some commands of `calicoctl`. Regardless of this problem, calico seems to be working fine.

```
$  sudo ETCD_AUTHORITY=172.17.8.102:2379 calicoctl pool show
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
+----------------+-------------------+
|   IPv4 CIDR    |      Options      |
+----------------+-------------------+
| 192.168.0.0/16 | ipip,nat-outgoing |
+----------------+-------------------+
+--------------------------+---------+
|        IPv6 CIDR         | Options |
+--------------------------+---------+
| fd80:24e2:f998:72d6::/64 |         |
+--------------------------+---------+
```
```
$ sudo ETCD_AUTHORITY=172.17.8.103:2379 calicoctl status
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
calico-node container is running. Status: Up 2 hours
Running felix version 1.4.0rc2

IPv4 BGP status
IP: 10.1.3.2    AS Number: 64511 (inherited)
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
Couldn't connect to bird.
IPv6 BGP status
No IPv6 address configured.```


I know this issue is related to the bug in bash rather than to you but I wanted to let you know.

**Comment by fasaxc** [comment] 2016-07-22 11:46
Thanks a lot for tracking this down @hectorj2f.  Someone else had reported the issue as #1063 but we hadn't managed to find the cause.  I've copied your comment over there and I'm going to close this one as a dupe so we get the whole trail.

**Closed by fasaxc** 2016-07-22 11:46 UTC
